Added support to conda version 4.4 and above (#52)
* To solve Conda new config location

It solves https://github.com/conda-tools/conda-execute/issues/50

* Added support to conda version 4.4 and above

To solve https://github.com/conda-tools/conda-execute/issues/50

* Update conda_interface.py

* Update to add conda version 4.5.3

* Correct versions Conda to 4.5.3 and Python to 3.5

* Trying to add conda 4.4 compatibility

* Take 2 - UnlinkLinkTransation Conda 4.4 and above

* Trying to add 4.4 compatibility using Solver

* Take two - to solve mismatching MatchSpec

* Added temporal comments

* Take 3 - Using Solver

* Compatibility to conda 4.4 - clean the code

Added compatibility with conda 4.4 and above by using core.Solver and models.match_spec.MatchSpec

* Remove comments to fully test patch

* Added Python 3.5 and removed 3.4

Conda in TravisCI was unable to create the env using Python 3.4.
Error was:
conda install --yes python=$PYTHON_VERSION --file requirements.txt
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.4
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> readline=7
  - urllib3 -> ipaddress -> python[version='>=2.7,<2.8.0a0'] -> tk=8.6

* Solve hopefully conda_42 incompatibly

Changed back to common.yaml for conda_42